import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument } from 'pdf-lib';
import sharp from 'sharp';
import { buildAcme } from './acme.js';
import { buildBlueRidgeClean } from './blueRidge.js';
import { SAMPLES, verifySpec } from './data.js';
import { degrade } from './degrade.js';
import { buildNorthwind } from './northwind.js';
import { buildZenith } from './zenith.js';

/**
 * Generate all four sample invoices.
 *
 * Everything is derived from `data.ts`, so the documents and the eval
 * expectations cannot drift apart. The run refuses to write anything if a
 * spec's own arithmetic does not balance — a fixture that lies about its own
 * totals would make every downstream accuracy number meaningless.
 */

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..', '..', '..');
const INPUT_DIR = join(ROOT, 'samples', 'input');
const REFERENCE_DIR = join(ROOT, 'samples', 'reference');
const TRUTH_FILE = join(ROOT, 'samples', 'truth.json');

const A4 = { width: 595.28, height: 841.89 };

/** Wrap a raster as a single-page PDF with NO text layer — a real scan. */
const imageToPdf = async (jpeg: Buffer): Promise<Buffer> => {
  const pdf = await PDFDocument.create();
  const img = await pdf.embedJpg(jpeg);
  const page = pdf.addPage([A4.width, A4.height]);

  // Fit, preserving aspect. The degraded image is slightly larger than the
  // original because rotation expands the canvas.
  const scale = Math.min(A4.width / img.width, A4.height / img.height);
  const w = img.width * scale;
  const h = img.height * scale;
  page.drawImage(img, { x: (A4.width - w) / 2, y: (A4.height - h) / 2, width: w, height: h });

  return Buffer.from(await pdf.save());
};

const kb = (b: Buffer) => `${(b.length / 1024).toFixed(0)} KB`;

const main = async () => {
  // ── refuse to generate documents from a fixture that contradicts itself ──
  const problems = SAMPLES.flatMap(verifySpec);
  if (problems.length) {
    console.error('Sample specs are internally inconsistent — refusing to generate:');
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }

  await mkdir(INPUT_DIR, { recursive: true });
  await mkdir(REFERENCE_DIR, { recursive: true });

  console.log('Generating samples...\n');

  // ── #1 clean PDF ──────────────────────────────────────────────────────
  const acme = await buildAcme();
  await writeFile(join(INPUT_DIR, 'acme-supplies.pdf'), acme);
  console.log(`  acme-supplies.pdf      ${kb(acme).padStart(8)}   clean text PDF`);

  // ── #2 label-variance PDF ─────────────────────────────────────────────
  const northwind = await buildNorthwind();
  await writeFile(join(INPUT_DIR, 'northwind-trading.pdf'), northwind);
  console.log(`  northwind-trading.pdf  ${kb(northwind).padStart(8)}   label variance, INR, GST`);

  // ── #3 degraded scan ──────────────────────────────────────────────────
  const { png: clean, targets } = await buildBlueRidgeClean();
  // Keep the pre-degradation render: it is the evidence that #3 is adversarial
  // by construction rather than an accident of a bad generator.
  await writeFile(join(REFERENCE_DIR, 'blue-ridge-before-degradation.png'), clean);

  const degraded = await degrade(clean, targets);
  await writeFile(join(REFERENCE_DIR, 'blue-ridge-after-degradation.jpg'), degraded);

  const scanPdf = await imageToPdf(degraded);
  await writeFile(join(INPUT_DIR, 'blue-ridge-scan.pdf'), scanPdf);
  const meta = await sharp(degraded).metadata();
  console.log(
    `  blue-ridge-scan.pdf    ${kb(scanPdf).padStart(8)}   scanned, no text layer ` +
      `(${meta.width}x${meta.height})`,
  );

  // ── #4 messy xlsx ─────────────────────────────────────────────────────
  const zenith = buildZenith();
  await writeFile(join(INPUT_DIR, 'zenith-parts.xlsx'), zenith);
  console.log(`  zenith-parts.xlsx      ${kb(zenith).padStart(8)}   offset origin, swapped cols`);

  // ── ground truth for the eval harness ─────────────────────────────────
  await writeFile(
    TRUTH_FILE,
    JSON.stringify(
      {
        note:
          'Ground truth for `npm run eval`. Generated by samples/generate — do not hand-edit. ' +
          '`expected` is what a PERFECT extraction returns: the values as PRINTED. Where the ' +
          'document leaves a cell blank, expected is null; producing a number there would mean ' +
          'the model invented data the document does not contain.',
        generatedAt: new Date().toISOString(),
        samples: SAMPLES,
      },
      null,
      2,
    ),
  );
  console.log(`\n  samples/truth.json     ground truth for the eval harness`);

  console.log('\nPlanted difficulty in blue-ridge-scan.pdf:');
  for (const f of SAMPLES.find((s) => s.key === 'blueridge')!.mustFlag) {
    console.log(`  - ${f.field.padEnd(26)} ${f.why}`);
  }
  console.log(
    '\nIf extraction handles #3 cleanly, degrade harder (samples/generate/src/degrade.ts).\n' +
      'Tune the GENERATOR, never the prompt.\n',
  );
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
